### ISSUE TITLE
HTTP/1.0 500 Internal Server Error

### ISSUE THREAD

**Issue by jahgsfbcnsads** [hthiery/python-fritzhome#12]
I get this error message upon trying to switch my Dect 300 with this command:
fritzhome (the login stuff) switch on (the ain of the device)

fritzhome -f 192.168.178.1 -u Gereon -p gereon switch on 119590373448

Traceback (most recent call last):
  File "/usr/local/bin/fritzhome", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pyfritzhome/cli.py", line 187, in main
    args.func(fritzbox, args)
  File "/usr/local/lib/python3.5/dist-packages/pyfritzhome/cli.py", line 87, in switch_on
    fritz.set_switch_state_on(args.ain)
  File "/usr/local/lib/python3.5/dist-packages/pyfritzhome/fritzhome.py", line 172, in set_switch_state_on
    return self._aha_request('setswitchon', ain=ain, rf=bool)
  File "/usr/local/lib/python3.5/dist-packages/pyfritzhome/fritzhome.py", line 105, in _aha_request
    return bool(int(plain))
ValueError: invalid literal for int() with base 10: 'HTTP/1.0 500 Internal Server Error\nContent-Length: 0\nContent-Type: text/plain; charset=utf-8\nX-Frame-Options: SAMEORIGIN\nX-Content-Type-Options: nosniff\nX-XSS-Protection: 1; mode=block'

**Comment by hthiery** [comment]
Please send the output with debug enabled. Also the info about uses Fritzbox model anderen firmware version.
