### ISSUE TITLE
Switch device does not have devicelock entry

### ISSUE THREAD

**Issue by hthiery** [hthiery/python-fritzhome#2]
fritz 6490 Cable and OS version 6.51

```
DEBUG:pyfritzhome.fritzhome:<device functionbitmask="896" fwversion="03.59" id="16" identifier="08761 0373130" manufacturer="AVM" productname="FRITZ!DECT 200">
        <present>1</present>
        <name>FRITZ!DECT 200 #1</name>
        <switch>
                <state>1</state>
                <mode>manuell</mode>
                <lock>1</lock>
        </switch>
        <powermeter>
                <power>114580</power>
                <energy>87830</energy>
        </powermeter>
        <temperature>
                <celsius>220</celsius>
                <offset>0</offset>
        </temperature>
</device>

INFO:pyfritzhome.fritzhome:logout
Traceback (most recent call last):
  File "/usr/bin/fritzhome", line 11, in <module>
    load_entry_point('pyfritzhome==0.3.3', 'console_scripts', 'fritzhome')()
  File "/usr/lib/python3.6/site-packages/pyfritzhome/cli.py", line 153, in main
    args.func(fritzbox, args)
  File "/usr/lib/python3.6/site-packages/pyfritzhome/cli.py", line 12, in list_all
    devices = fritz.get_devices()
  File "/usr/lib/python3.6/site-packages/pyfritzhome/fritzhome.py", line 133, in get_devices
    device = FritzhomeDevice(self, node=element)
  File "/usr/lib/python3.6/site-packages/pyfritzhome/fritzhome.py", line 239, in __init__
    self._update_from_node(node)
  File "/usr/lib/python3.6/site-packages/pyfritzhome/fritzhome.py", line 272, in _update_from_node
    self.device_lock = bool(get_node_value(n, 'devicelock'))
  File "/usr/lib/python3.6/site-packages/pyfritzhome/fritzhome.py", line 28, in get_node_value
    return get_text(node.getElementsByTagName(name)[0].childNodes)
IndexError: list index out of range

```

**Comment by Dominion0815** [comment]
Hi,

I have testet your new version and both devices are listed correctly, but afterwards I get this error:

```
DEBUG:pyfritzhome.fritzhome:<device functionbitmask="896" fwversion="03.59" id="16" identifier="08761 0373130" manufacturer="AVM" productname="FRITZ!DECT 200">
	<present>1</present>
	<name>FRITZ!DECT 200 #1</name>
	<switch>
		<state>1</state>
		<mode>manuell</mode>
		<lock>1</lock>
	</switch>
	<powermeter>
		<power>99560</power>
		<energy>116972</energy>
	</powermeter>
	<temperature>
		<celsius>220</celsius>
		<offset>0</offset>
	</temperature>
</device>

DEBUG:pyfritzhome.fritzhome:<device functionbitmask="320" fwversion="03.50" id="17" identifier="11959 0812272" manufacturer="AVM" productname="Comet DECT">
	<present>1</present>
	<name>Comet DECT #2</name>
	<temperature>
		<celsius>230</celsius>
		<offset>-10</offset>
	</temperature>
	<hkr>
		<tist>46</tist>
		<tsoll>45</tsoll>
		<absenk>32</absenk>
		<komfort>45</komfort>
	</hkr>
</device>

INFO:pyfritzhome.fritzhome:logout
Traceback (most recent call last):
  File "/usr/bin/fritzhome", line 11, in <module>
    load_entry_point('pyfritzhome==0.3.4', 'console_scripts', 'fritzhome')()
  File "/usr/lib/python3.6/site-packages/pyfritzhome/cli.py", line 163, in main
    args.func(fritzbox, args)
  File "/usr/lib/python3.6/site-packages/pyfritzhome/cli.py", line 19, in list_all
    devices = fritz.get_devices()
  File "/usr/lib/python3.6/site-packages/pyfritzhome/fritzhome.py", line 127, in get_devices
    device = FritzhomeDevice(self, node=element)
  File "/usr/lib/python3.6/site-packages/pyfritzhome/fritzhome.py", line 231, in __init__
    self._update_from_node(node)
  File "/usr/lib/python3.6/site-packages/pyfritzhome/fritzhome.py", line 254, in _update_from_node
    self.lock = bool(int(get_node_value(n, 'lock')))
  File "/usr/lib/python3.6/site-packages/pyfritzhome/fritzhome.py", line 22, in get_node_value
    return get_text(node.getElementsByTagName(name)[0].childNodes)
IndexError: list index out of range
```
