### ISSUE TITLE
Exception: GOTOBLAS_MAIN_FREE

### ISSUE THREAD

**Issue by chemelli74** [hthiery/python-fritzhome#24]
As requested by @escoand, I'm opening a issue for this problem of the library:

```
2020-05-31 23:15:20 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.xxx.1 for fritzbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/fritzbox/__init__.py", line 79, in async_setup_entry
    await hass.async_add_executor_job(fritz.login)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyfritzhome/fritzhome.py", line 115, in login
    secret=secret)
  File "/usr/local/lib/python3.7/site-packages/pyfritzhome/fritzhome.py", line 62, in _login_request
    plain = self._request(url, params)
  File "/usr/local/lib/python3.7/site-packages/pyfritzhome/fritzhome.py", line 49, in _request
    rsp = self._session.get(url, params=params, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 521, in request
    prep.url, proxies, stream, verify, cert
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 697, in merge_environment_settings
    env_proxies = get_environ_proxies(url, no_proxy=no_proxy)
  File "/usr/local/lib/python3.7/site-packages/requests/utils.py", line 769, in get_environ_proxies
    return getproxies()
  File "/usr/local/lib/python3.7/urllib/request.py", line 2480, in getproxies_environment
    for name, value in os.environ.items():
  File "/usr/local/lib/python3.7/_collections_abc.py", line 744, in __iter__
    yield (key, self._mapping[key])
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'GOTOBLAS_MAIN_FREE'
```

Simone

**Comment by chemelli74** [comment]
Did you get time to check this issue ?

Thx,

Simone

**Comment by chemelli74** [comment]
Hi, any feedback ?

Thank you in advance,

Simone

**Comment by chemelli74** [comment]
Any news ?

**Comment by chemelli74** [comment]
No progress, closing.

Simone
