### ISSUE TITLE
Random error: login failed

### ISSUE THREAD

**Issue by chemelli74** [hthiery/python-fritzhome#26]
Sometimes I get this log entry:

```
2020-07-29 01:27:47 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry FRITZ!Box 7590 for fritzbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 219, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/fritzbox/__init__.py", line 79, in async_setup_entry
    await hass.async_add_executor_job(fritz.login)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyfritzhome/fritzhome.py", line 118, in login
    raise LoginError(self._user)
pyfritzhome.errors.LoginError: login for user="admin" failed
```

Usually to recover it's enough to just wait for a new polling cycle, sometimes instead a restart of HA is needed.

Simone

**Comment by chemelli74** [comment]
Any progress?

**Comment by chemelli74** [comment]
No longer valid with latest version.
