### ISSUE TITLE
new feature requests - FRITZ!Smart Gateway - support for Zigbee Devices

### ISSUE THREAD

**Issue by Peter1980FFM** [hthiery/python-fritzhome#90]
Hallo I use the  - FRITZ!Smart Gateway - in Home Assistant i see, that some Devices not Fully Supportet.
support for zigbee units (see chapter 1.2 in [avm api docs](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf))

If you need some Examples write me Back

**Comment by Peter1980FFM** [comment]
[AVM_Zigbee_Devices.xlsx](https://github.com/hthiery/python-fritzhome/files/13801440/AVM_Zigbee_Devices.xlsx)
Add the Device Information from the not correct working Devices

**Comment by Peter1980FFM** [comment]
@mib1185 i just create the Json file from my Fritzbox
[overview.json](https://github.com/hthiery/python-fritzhome/files/13852799/overview.json)
Groups are Devices 82 - 84
Device 81 is a Window Sensor in Homeassistant Device not get the Batterie Value
Device 79 is a Fritz Dect 440 Device in Home assistant are the 4 Buttons missing 
Device 78 is aFritz Dect 400 Button in Home Assistan it only show the Batterie not the Buttons
Device 75 is a On/Off Button in Home Assistan it is not shown
Device 73 is a Zigbee Repeater and not show in Homeassistant
Device 69 i a Zigbee One Button and not show in Homeassitant
Device 66/67 is a Open/Close Button in Home Assistan it is not shown
Device 64 is a shutter in Home Assistan it is not shown in Home Assistant Batterie is Missing
Devices 50/51/52 aber one power strip AVM Make 3 Devices but all work in Home Assistant
Device 34 / 36 / 38 / 40 / 42  / 44 are only CCT Ligts but in Home Assistant show as Full collor Devices in Fritzbox CCT 
Devices 9-12 and 4-7 are 4 ch Zigbee Devices and Each Channel is a Singel Entry 

I have seen in the Json File the AVM makes for Every Button on Zigbee Device a One Device in the Json file 
I hope i could help a Littel bit.

i have Order a Fritz DECT 350 Sensor but Hermes is not abel to Deliver so i can´t test it and a new oder is not posible its sold out yeah 
If you need further support contact me

**Comment by mib1185** [comment]
i've started to do some pre-work with #91, #94 and #95. there is a further PR in my queue which will improve the interoperability with zigbee devices (_and maybe other dect devices as well_)

**Comment by Peter1980FFM** [comment]
If you need the json for the DECT 350 let me know

**Comment by mib1185** [comment]
@Peter1980FFM Are you willing and able to help with some development tests in your HA installation?
If yes, I would like to provide you a custom version of the `fritzbox` integration which relies on the current development (_open PRs above_) so you could test if this will improve the compatibility with your zigbee devices.
Feel free to contact me via discord (_my name is `mib1185`_)

**Comment by mib1185** [comment]
ok, than let's go with the very first step

### 1. create a backup !!!

### 2. now install the custom fritzbox component:

via HACS:
- add `https://github.com/mib1185/hass_fritzbox.git` as custom repository
- you should find the "Custom AVM FRITZ!SmartHome - only for development purpose" integration
- install it and restart HA

or manually:
- copy the whole custom [fritzbox](https://github.com/mib1185/hass_fritzbox/tree/main/custom_components/fritzbox) into your `/config/custom_components` folder (_should be `/config/custom_components/fritzbox` afterwards_)
- restart HA

---

as soon as you got the custom fritzbox component installed, please restart HA, download and provide the [diagnostics](https://www.home-assistant.io/integrations/diagnostics) data and check if there are any noticeable improvements. 

expected improvements:
- missing battery values should be shown
- buttons will still not be added (_because the Fritz!Box api is pull only_), but the possible sensors (_eq. temperature and humidity_) should be shown
- same goes for repeaters - their possible sensors should be shown, but not the repeater itself

**Comment by Peter1980FFM** [comment]
I cant check it dont can bei Installed 
![image](https://github.com/hthiery/python-fritzhome/assets/45266139/cd5056db-3916-49ec-90bc-8edb55fea7ff)

**Comment by Peter1980FFM** [comment]
After reboot 
![image](https://github.com/hthiery/python-fritzhome/assets/45266139/7c427d55-a7d9-45f0-8e2c-a1ee62ac5435)
and want to be reboot and than comes the Message above.
i junst switch on debug in the logs i found
Home Assistant Core
Error setting up integration fritzbox - received exception
09:34:40 – (FEHLER) util/package.py

**Comment by mib1185** [comment]
@Peter1980FFM i've uploaded a new version of the custom component. would be great if you could test this new one

**Comment by mib1185** [comment]
this is still the old version "0.0.1.dev0" 🤔 
how did you install it? if hacs, please try to search for updates, so that "0.0.1.dev1" will be shown

**Comment by Peter1980FFM** [comment]
Look not so good 
![image](https://github.com/hthiery/python-fritzhome/assets/45266139/067f5c89-e35d-4462-9bd0-47b753a11e0a)
[home-assistant_fritzbox_2024-01-15T19-14-36.194Z.log](https://github.com/hthiery/python-fritzhome/files/13942356/home-assistant_fritzbox_2024-01-15T19-14-36.194Z.log)

**Comment by mib1185** [comment]
ok, next try ... a new version -> "0.0.1.dev2" ... it contains now the just fresh released [0.6.10](https://github.com/hthiery/python-fritzhome/releases/tag/0.6.10)

**Comment by Peter1980FFM** [comment]
looks a littel bit better
![image](https://github.com/hthiery/python-fritzhome/assets/45266139/14645024-a184-4a69-bece-b99c0ec8f8fc)
some Device are 2 time in the List now
Groups are show unknown
![image](https://github.com/hthiery/python-fritzhome/assets/45266139/a73f1137-045d-4759-8563-fda368c72b38)
[home-assistant_fritzbox_2024-01-15T19-51-49.953Z.log](https://github.com/hthiery/python-fritzhome/files/13942570/home-assistant_fritzbox_2024-01-15T19-51-49.953Z.log)

**Comment by mib1185** [comment]
Please download and provide the [diagnostics](https://www.home-assistant.io/integrations/diagnostics) data.
The `unknown` model is expected for groups, since they do not have a model.

**Comment by mib1185** [comment]
Further please also provide screenshot from the devices detailed page (_eq. both "Esszimmer Fenster unten"_)

**Comment by Peter1980FFM** [comment]
[config_entry-fritzbox-76a34de47a331963a19f9a3241f29eef.json (7).txt](https://github.com/hthiery/python-fritzhome/files/13942652/config_entry-fritzbox-76a34de47a331963a19f9a3241f29eef.json.7.txt)

![image](https://github.com/hthiery/python-fritzhome/assets/45266139/c3c28bd1-7c64-407d-806a-60378fd60914)

![image](https://github.com/hthiery/python-fritzhome/assets/45266139/7778a200-6e41-4777-b259-93a3ffe61ce0)

![image](https://github.com/hthiery/python-fritzhome/assets/45266139/241ef65a-fa0c-43f7-8a99-df982389d6ed)

![image](https://github.com/hthiery/python-fritzhome/assets/45266139/ede027c4-b6fd-4d3b-87b1-c22f74c16248)

**Comment by mib1185** [comment]
mehh ... we need some kind of `identifiers` migration within the already existing devicees ... will work on it and come back with an updated version ^^

**Comment by mib1185** [comment]
are there any of these duplicated devices, where both has entities?
If you have console access (_eq. via the terminal add-on or ssh_) than it would be great if you could capture the actual device registry data like follows

change into `/config/.storage` directory
```bash
$ cd /config/.storage
```

get the id of the current fritzbox configuration entry
```bash
$ cat core.config_entries | jq '.data.entries[] | select(.domain == "fritzbox" and .source != "ignore") | .entry_id'
"4c042584ff6711eaa7a09baa9efee9fd"
```

now get all device registry entries connected to this configuration entry (_replace `4c042584ff6711eaa7a09baa9efee9fd` with the id from above_) and provide all the output
```bash
$ cat core.device_registry | jq '.data.devices[] | select(.config_entries[0] == "4c042584ff6711eaa7a09baa9efee9fd")'
```

**Comment by mib1185** [comment]
ok, here we go -> new version "0.0.1.dev3" with `identifiers`  migration logic.

the duplicated devices may remain, but all entities should now be attached to the "correct" device (_usually this with a correct firmware version information_). if this is the case, please delete these "empty" devices and restart HA ... they should not re-occur

**Comment by Peter1980FFM** [comment]
i can not delet the unknown devices 
![image](https://github.com/hthiery/python-fritzhome/assets/45266139/ffc089f1-14c2-4829-a00f-368eece87514)

**Comment by mib1185** [comment]
please open the detail pages of these devices and provide some screenshots.
on the top right corner of the detail page, you should find the delete option via the edit (_pencil _) dialog.

what ist the current overall state? are the devices and entities now as expected?

**Comment by Peter1980FFM** [comment]
Deletion not work I dont know why, just go back to my backup an Install from git again, now it looks better,
some Device miss the Firmware Information but the rest looks good

**Comment by mib1185** [comment]
Could you please download and provide the [diagnostics](https://www.home-assistant.io/integrations/diagnostics) data again?
and provide some screenshots of the devices with missing/wrong firmware infomration?

**Comment by Peter1980FFM** [comment]
Good Morning 3 Examples

![image](https://github.com/hthiery/python-fritzhome/assets/45266139/4ec70ff2-a1ec-4338-a6be-7f9adf5dbea7)
![image](https://github.com/hthiery/python-fritzhome/assets/45266139/a1f019e0-39b4-4198-a1c2-d4a0a0bb901f)
![image](https://github.com/hthiery/python-fritzhome/assets/45266139/f3e6c8db-7581-4799-b07c-bcd09c355ec3)
![image](https://github.com/hthiery/python-fritzhome/assets/45266139/7db481f9-844a-450c-8505-80d5fb42aef3)
![image](https://github.com/hthiery/python-fritzhome/assets/45266139/fcde3441-de90-4c44-83b4-ac0355c7b41e)
![image](https://github.com/hthiery/python-fritzhome/assets/45266139/ce9361e0-623a-4732-8f01-f542ba266236)
[config_entry-fritzbox-76a34de47a331963a19f9a3241f29eef.json (6).txt](https://github.com/hthiery/python-fritzhome/files/13946213/config_entry-fritzbox-76a34de47a331963a19f9a3241f29eef.json.6.txt)

**Comment by mib1185** [comment]
hi @Peter1980FFM 
sorry for late response, was busy these days.
i've checked the last diagnostics data and the screenshots - ich think we are near to get this finished and ready 👍 
Would be great if you could provide a fresh set of debug logs - because the `fritzbox` integration is now used as custom component the settings needs to be changed a bit like follows in your `configuration.yaml`:
```yaml
logger:
  default: info
  logs:
    custom_components.fritzbox: debug
    pyfritzhome: debug
```

**Comment by Peter1980FFM** [comment]
[home-assistant_fritzbox_2024-01-19T08-26-40.548Z.log](https://github.com/hthiery/python-fritzhome/files/13986364/home-assistant_fritzbox_2024-01-19T08-26-40.548Z.log)
Hi now the new Debug, i think i see somethingin the Debug Note, the main Device have the Firmware but the  Datatpoints not

**Comment by mib1185** [comment]
> the main Device have the Firmware but the Datatpoints not

correct, that's why i tried to create the `DeviceInfo` in the fritzbox component based on if it is the main device or a sub unit. But as long as the main device do not provide any data which are consumed for any sensor entity, the DeviceInfo (_with correct firmware_) is not created ... anyhow this will lead to a breaking change in HA for the fritzbox component, so i'm, working on it to make this breaking change as less impact and "user friendly" as possible.

**Comment by mib1185** [comment]
Hi @Peter1980FFM 
unfortunately there is no acceptable way to automatically migrate all device ids and their possible usage in automations and scripts, so it will now create so called repair issues, so that the user is informed when automations and scripts needs to be changed by the user
this is now included in the new "0.0.1.dev4" version, would be great if you could test it again - if possible with one your previous backups

**Comment by Peter1980FFM** [comment]
@mib1185 
got the error
Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 15:46:58 (1 occurrences)
Last logged: 15:46:58

Error setting up entry 192.168.122.24 for fritzbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fritzbox/__init__.py", line 105, in async_setup_entry
    hass.data[DATA_INSTANCES][automation.DOMAIN]
TypeError: unsupported operand type(s) for +: 'EntityComponent' and 'EntityComponent'
![image](https://github.com/hthiery/python-fritzhome/assets/45266139/a4f4b589-041c-4153-8fef-fa65b4511241)

**Comment by mib1185** [comment]
mehhh ... forgot to upload the latest code ... new version "0.0.1.dev5" is now ready

**Comment by Peter1980FFM** [comment]
better :-)
![image](https://github.com/hthiery/python-fritzhome/assets/45266139/11aecf46-cd1e-42d0-a858-ad63842f6bde)
[home-assistant_fritzbox_2024-01-21T15-42-12.935Z.log](https://github.com/hthiery/python-fritzhome/files/14001862/home-assistant_fritzbox_2024-01-21T15-42-12.935Z.log)

**Comment by Peter1980FFM** [comment]
The gray of the switch are ok the Device is not Connect now to the Gateway christmal is Over ;-)

**Comment by Peter1980FFM** [comment]
@mib1185 i found a Error when i want to update my Automations
![image](https://github.com/hthiery/python-fritzhome/assets/45266139/e139d0c8-5531-4481-8341-1eafbbb5fc87)

**Comment by mib1185** [comment]
there should be repair issues for every replaced device, which was used in any automation or script

**Comment by Peter1980FFM** [comment]
@mib1185  not Realy staple
i reboot home Assist
![image](https://github.com/hthiery/python-fritzhome/assets/45266139/022a9d4f-e796-4b57-b241-e44b8307de9d)

Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 16:54:51 (1 occurrences)
Last logged: 16:54:51
[home-assistant_fritzbox_2024-01-21T16-06-24.628Z.log](https://github.com/hthiery/python-fritzhome/files/14001963/home-assistant_fritzbox_2024-01-21T16-06-24.628Z.log)




Error setting up entry 192.168.122.24 for fritzbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fritzbox/__init__.py", line 102, in async_setup_entry
    automation_component: EntityComponent[automation.AutomationEntity] = hass.data[
                                                                         ^^^^^^^^^^
KeyError: 'automation'

After Manual Rebbot the Integration

![image](https://github.com/hthiery/python-fritzhome/assets/45266139/3a59bf93-de96-4b15-9484-05bc20c7534d)

**Comment by mib1185** [comment]
mehhh 😖  the automations seems not to be loaded in the first place, so the detection of issues couldn't work 🙄

**Comment by Peter1980FFM** [comment]
May the Automatic Repair is not the Solution :-( if you have more than one Entry in the Automation it only takes the Last one and Correct them but it not work i have to del it an make it new

**Comment by mib1185** [comment]
there is no automatic repair of scripts and automations - this is not possible.
It will just inform the user, that there are automations and scripts (_ the names of these automations and scripts are also shown_) to be fixed by the user manually.

**Comment by Peter1980FFM** [comment]
thank you good to know i will whait for the final releas or is anything to test in future?

**Comment by mib1185** [comment]
unfortunately even the final release will not have any automatic fixes. nevertheless I still need to solve the last issue you observed (_btw many thanks for all your testing yet 🤝_). Would be great if you could do some further tests as soon as I've I new development version ready

**Comment by robertkleinschuster** [comment]
What is the current state of Zigbee device support?

I would like to use Philips Hue Switches (4 Buttons) and Motion Sensors (that include a Motion, Brightness and Temperature Sensor)

In Home Assistant Philips Lightbulbs Seem to work fine but the Switches only Show up as Battery Level Sonsors and the Motion Sensors Show up as Battery and Alarm Sensors

BTW I am a software developer myself and lerning Python at the moment, i think with a bit of an introduction to the code i could help improve support for those things but I don't quite understand how the different device classes are instaciated yet from just looking at the code on GitHub.

Maybe i can checkout the repo and step debug the code to see whats going on with those devices.

**Comment by mib1185** [comment]
Hi @robertkleinschuster 
the Zigbee support is basically there, but the API of the Fritzbox does not provide push updates, so every device, which needs instant updates or reactions to be proper usable  (_eq. buttons and motion sensors_) are still not supported.
This is a limitation of the http api of the Fritzbox itself, those only AVM could change it, by adding some push update mechanism to their api.

**Comment by mib1185** [comment]
Hi @Peter1980FFM
sorry for the very long delay 🙈  But I've good news for you, proper support for zigbee devices (_and also other DECT devices with multiple units_) will be added directly in Home Assistant with https://github.com/home-assistant/core/pull/142845

**Comment by mib1185** [comment]
The PR has been merged in the HA core repo, so this feature will become available with next major release 2025.5
